### PR TITLE
Add syscon regsiters to the loadstore unit

### PR DESCRIPTION
**Pull request by shenki**
In https://github.com/micropython/micropython/issues/6937 @carlosedp points out that micropython suffers from the lack of syscon registers in chiselwatt. This is a really simple implementation that should get it going.

### CODE REVIEW

**Comment by mikey** [comment]
Ha I had the same patch but was working on making it generic. Here's mine rebased on your patch: https://github.com/mikey/chiselwatt/commits/syscon

**Comment by carlosedp** [comment]
Thanks Mikey, but what about adding the clock as a variable from Core.scala... like:

```diff
diff --git a/src/main/scala/Core.scala b/src/main/scala/Core.scala
index 8f24571..d46aa30 100644
--- a/src/main/scala/Core.scala
+++ b/src/main/scala/Core.scala
@@ -6,7 +6,7 @@ import Control._
 import Helpers._
 import InstructionHelpers._

-class Core(bits: Int, memSize: Int, memFileName: String, resetAddr: Int) extends Module {
+class Core(bits: Int, memSize: Int, memFileName: String, resetAddr: Int, clock: Int) extends Module {
   val io = IO(new Bundle {
     val tx = Output(UInt(1.W))
     val rx = Input(UInt(1.W))
@@ -40,7 +40,7 @@ class Core(bits: Int, memSize: Int, memFileName: String, resetAddr: Int) extends
   val multiplier = Module(new SimpleMultiplier(bits))
   val divider = Module(new SimpleDivider(bits))
   val mem = Module(new MemoryBlackBoxWrapper(bits, memWords, memFileName))
-  val loadStore = Module(new LoadStore(bits, memWords))
+  val loadStore = Module(new LoadStore(bits, memWords, clock))
   val control = Module(new Control(bits))

   val regFile = Module(new RegisterFile(32, bits, 3, 1, false))
@@ -59,7 +59,7 @@ class Core(bits: Int, memSize: Int, memFileName: String, resetAddr: Int) extends

   /* Blink an LED, this proves we are out of reset */
   val led = RegInit(0.U(1.W))
-  val (counterValue, counterWrap) = Counter(true.B, 50000000)
+  val (counterValue, counterWrap) = Counter(true.B, clock)
   when (counterWrap) {
     led := ~led
   }
diff --git a/src/main/scala/LoadStore.scala b/src/main/scala/LoadStore.scala
index 96a05ad..dd7bf3e 100644
--- a/src/main/scala/LoadStore.scala
+++ b/src/main/scala/LoadStore.scala
@@ -6,7 +6,7 @@ import Control._
 import Helpers._
 import LoadStoreByteReverse._

-class LoadStoreInput(val bits: Int) extends Bundle {
+class LoadStoreInput(val bits: Int, val clock: Int) extends Bundle {
   val a           = Input(UInt(bits.W))
   val b           = Input(UInt(bits.W))
   val data        = Input(UInt(bits.W))
```

This way it could be dynamically defined. Also what about adding the changes to dynamically get the SYSCON clock in the hello_world example and the Verilator uart.c module.

**Comment by carlosedp** [comment]
I also added the support for fetching clock from SYSCON to hello_world sample:

```diff
Found existing alias for "git". You should use: "g"
diff --git a/samples/hello_world/hello_world.c b/samples/hello_world/hello_world.c
index cba06e3..4b650c1 100644
--- a/samples/hello_world/hello_world.c
+++ b/samples/hello_world/hello_world.c
@@ -9,7 +9,9 @@

 static uint64_t potato_uart_base;

-#define PROC_FREQ 50000000
+#define SYSCON_BASE 0xc0000000 /* System control regs */
+#define SYS_REG_CLKINFO 0x20
+
 #define UART_FREQ 115200
 #define UART_BASE 0xc0002000

@@ -93,9 +95,11 @@ static unsigned long potato_uart_divisor(unsigned long proc_freq, unsigned long

 void potato_uart_init(void)
 {
+       uint64_t proc_freq;
        potato_uart_base = UART_BASE;

-       potato_uart_reg_write(POTATO_CONSOLE_CLOCK_DIV, potato_uart_divisor(PROC_FREQ, UART_FREQ));
+       proc_freq = *(volatile uint64_t *)(SYSCON_BASE + SYS_REG_CLKINFO);
+       potato_uart_reg_write(POTATO_CONSOLE_CLOCK_DIV, potato_uart_divisor(proc_freq, UART_FREQ));
 }

 int getchar(void)
```

**Comment by mikey** [comment]
@carlosedp want to post that hello_world update as a PR?

**Comment by carlosedp** [comment]
Sure, absolutely :)
I will also send an update to the hello_world, makefile and Dockerfile with the crossbuild ppc64le toolchain container.

**Comment by shenki** [comment]
I've added @mikey's commit to this PR.

**Comment by antonblanchard** [comment]
Thanks @shenki and @mikey!

**Pull request merged**
